permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Karl.Ai"
  description: |
    My personal graphic design portfolio majoring in package and print design, minoring in UX and Ui design. With a slight interests in motion.
  font_url: "https://fonts.googleapis.com/css?family=Raleway:500|Roboto+Slab:300&display=swap"
  colors:
    background: "--color-text"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-text"
  rationales:
    typefaces.primary: |
      Raleway was chosen because it's bold and unique look while still being an elegnat typeface make it a strong partner to Roboto.
    typefaces.secondary: |
      Roboto Slab has mechanical form that focuses on ensuring reading rhythm, this humanist approach is a good partner to the more elegant Raleway.
    colors.primary: |
      The primary colour is a darker colour to help set a modern and professional mood. Should only be used for the background and headers.
    colors.secondary: |
      The secondary colour is an brown used for less important elements for the website.
    colors.highlight: |
      The highlight colour is used to accentuate elements on the current webpage.
    colors.text: |
      As per it's namesake will be used mostly for the text but, will also be used for neutral state elements.
