patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Solo Travellers"
      - name: subheading
        type: string
        example: "UI and Ux Design"
      - name: text
        type: string
        example: "Project focusing on providing a mobile application for solo female travellers to connect."
